# Generated by Django 5.2.13 on 2026-09-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllTrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainno', models.CharField(max_length=100)),
                ('trainname', models.CharField(max_length=100)),
                ('start', models.IntegerField()),
                ('dest', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('total_seats', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('food_supply', models.BooleanField()),
            ],
        ),
    ]
