# Generated by Django 5.2.13 on 2026-09-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alltrain',
            name='dest',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='alltrain',
            name='start',
            field=models.CharField(max_length=100),
        ),
    ]
